action_mode: delta
activation_fn: Tanh
batch_size: 32
beam_param_combiner: GeometricMean
beam_param_combiner_args: {}
beam_param_combiner_weights:
- 1
- 1
- 1
- 1
beam_param_transform: SoftPlus
clip_magnets: true
clip_range: 0.2
clip_range_vf: null
ent_coef: 0.007668618764756837
final_combiner: SmoothMax
final_combiner_args:
  alpha: -0.5
final_combiner_weights:
- 3
- 1
- 0.5
frame_stack: 1
gae_lambda: 0.95
gamma: 0.98
incoming_mode: random
learning_rate: 3.29559373261337e-05
log_std_init: -1.0468292139247728
lr_schedule: constant
magnet_change_combiner: GeometricMean
magnet_change_combiner_args: {}
magnet_change_combiner_weights:
- 1
- 1
- 1
- 1
- 1
magnet_change_transform: SoftPlus
magnet_init_mode: random
max_episode_steps: 50
max_grad_norm: 0.6
max_misalignment: 0.0005
max_quad_delta: 72
max_steerer_delta: 0.0061782
misalignment_mode: random
n_envs: 40
n_epochs: 20
n_steps: 32
net_arch: small
normalize_observation: true
normalize_reward: false
ortho_init: true
rescale_action: true
run_name: atomic-sweep-282
running_obs_norm: false
sb3_device: auto
sde_sample_freq: -1
target_beam_mode: random
target_kl: null
target_threshold: null
threshold_hold: 1
total_timesteps: 5000000
use_sde: false
vec_env: subproc
vf_coef: 0.6302484260098792
