action_mode: delta
batch_size: 100
beam_param_combiner: Mean
beam_param_combiner_args: {}
beam_param_combiner_weights:
- 1
- 1
- 1
- 1
beam_param_transform: SoftPlus
clip_magnets: true
ent_coef: 0.01
final_combiner: SmoothMax
final_combiner_args:
  alpha: -5
final_combiner_weights:
- 2
- 1
- 0.5
frame_stack: 1
gamma: 0.99
incoming_mode: random
learning_rate: 0.0003
magnet_change_combiner: Mean
magnet_change_combiner_args: {}
magnet_change_combiner_weights:
- 1
- 1
- 1
- 1
- 1
magnet_change_transform: Sigmoid
magnet_init_mode: random
max_episode_steps: 50
max_misalignment: 0.0005
max_quad_delta: 72
max_steerer_delta: 0.0061782
misalignment_mode: random
n_envs: 40
n_steps: 100
normalize_observation: true
normalize_reward: false
rescale_action: true
run_name: colorful-sponge-28
running_obs_norm: false
sb3_device: auto
target_beam_mode: random
target_threshold: null
threshold_hold: 1
total_timesteps: 10000000
vec_env: subproc
