action_mode: delta
activation_fn: Tanh
batch_size: 128
beam_param_combiner: Mean
beam_param_combiner_args: {}
beam_param_combiner_weights:
  - 1
  - 1
  - 1
  - 1
beam_param_transform: ClippedLinear
clip_magnets: true
clip_range: 0.2
clip_range_vf: null
ent_coef: 0.01
final_combiner: Mean
final_combiner_args: {}
final_combiner_weights:
  - 3
  - 0.5
  - 0.5
frame_stack: 1
gae_lambda: 0.95
gamma: 0.99
incoming_mode: random
# learning_rate: !!python/name:rl_zoo3.utils.func ''
log_std_init: -2.3
lr_schedule: linear
magnet_change_combiner: Mean
magnet_change_combiner_args: {}
magnet_change_combiner_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
magnet_change_transform: Sigmoid
magnet_init_mode: random
max_episode_steps: 50
max_grad_norm: 0.5
max_misalignment: 0.0005
max_quad_delta: 30.0
max_quad_setting: 30.0
max_steerer_delta: 0.0061782
misalignment_mode: random
n_envs: 40
n_epochs: 10
n_steps: 128
net_arch: small
normalize_observation: true
normalize_reward: false
ortho_init: true
polished_donkey_reward: false
rescale_action: true
run_name: vital-breeze-514
running_obs_norm: false
sb3_device: auto
sde_sample_freq: -1
target_beam_mode: random
target_kl: null
target_threshold: null
threshold_hold: 1
total_timesteps: 5000000
use_sde: false
vec_env: subproc
vf_coef: 0.5
