
env:
  # Fixed parameters for the evaluation
  backend: cheetah
  backend_args:
    incoming_mode: random
    misalignment_mode: random
    max_misalignment: 1.0e-4
  max_quad_setting: 30.0
  max_quad_delta: 30.0
  max_steerer_delta: 6.1782e-3
  magnet_init_mode: random
  target_beam_mode: [0, 0, 0, 0]
  threshold_hold: 1
  clip_magnets: true
  target_threshold: null  # 2e-5 m is estimated screen resolution
  render_mode: "rgb_array"
  # You can change the following parameters to your liking
  action_mode: direct

env_wrapper:
  # Fixed parameters for the evaluation
  max_episode_steps: 200
  # You can change the following parameters to your liking
  normalize_observation: true
  running_obs_norm: false
  rescale_action: true