name: test_notebook

on:
  push:
    branches: [master, prepare-challenge-part1]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        include:
          - os: macos-latest
            python-version: "3.12"
          - os: windows-latest
            python-version: "3.12"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: "latest"
          environment-file: environment.yml
      - name: Test the notebook by running it
        run: |
          jupyter execute notebooks/tutorial_part1.ipynb
